# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

ProductCategory.create(name: "vegetables");
ProductCategory.create(name: "fruits");
ProductCategory.create(name: "detergent");
ProductCategory.create(name: "dairy");
ProductCategory.create(name: "frozen food");

Product.create({name: "Bakłażan", product_category_id: 1})
Product.create({name: "Batat", product_category_id: 1})
Product.create({name: "Bób", product_category_id: 1})
Product.create({name: "Brokuł", product_category_id: 1})
Product.create({name: "Brukiew", product_category_id: 1})
Product.create({name: "Brukselka", product_category_id: 1})
Product.create({name: "Burak", product_category_id: 1})
Product.create({name: "Cebula", product_category_id: 1})
Product.create({name: "Chrzan", product_category_id: 1})
Product.create({name: "Ciecierzyca", product_category_id: 1})
Product.create({name: "Cukinia", product_category_id: 1})
Product.create({name: "Cykoria", product_category_id: 1})
Product.create({name: "Czosnek", product_category_id: 1})
Product.create({name: "Dynia", product_category_id: 1})
Product.create({name: "Fasola", product_category_id: 1})
Product.create({name: "Fasolka szparagowa", product_category_id: 1})
Product.create({name: "Fenkuł (koper włoski)", product_category_id: 1})
Product.create({name: "Groch", product_category_id: 1})
Product.create({name: "Jarmuż", product_category_id: 1})
Product.create({name: "Kalafior", product_category_id: 1})
Product.create({name: "Kalarepa", product_category_id: 1})
Product.create({name: "Kapar", product_category_id: 1})
Product.create({name: "Kapusta", product_category_id: 1})
Product.create({name: "Karczoch", product_category_id: 1})
Product.create({name: "Koper", product_category_id: 1})
Product.create({name: "Kukurydza", product_category_id: 1})
Product.create({name: "Marchew", product_category_id: 1})
Product.create({name: "Miechunka", product_category_id: 1})
Product.create({name: "Ogórek", product_category_id: 1})
Product.create({name: "Oliwka", product_category_id: 1})
Product.create({name: "Papryka", product_category_id: 1})
Product.create({name: "Pasternak", product_category_id: 1})
Product.create({name: "Patison", product_category_id: 1})
Product.create({name: "Pietruszka", product_category_id: 1})
Product.create({name: "Pomidor", product_category_id: 1})
Product.create({name: "Por", product_category_id: 1})
Product.create({name: "Rabarbar", product_category_id: 1})
Product.create({name: "Roszponka", product_category_id: 1})
Product.create({name: "Rukola", product_category_id: 1})
Product.create({name: "Rzepa", product_category_id: 1})
Product.create({name: "Rzeżucha", product_category_id: 1})
Product.create({name: "Rzodkiew", product_category_id: 1})
Product.create({name: "Rzodkiewka", product_category_id: 1})
Product.create({name: "Sałata", product_category_id: 1})
Product.create({name: "Seler", product_category_id: 1})
Product.create({name: "Soczewica", product_category_id: 1})
Product.create({name: "Soja", product_category_id: 1})
Product.create({name: "Szalotka", product_category_id: 1})
Product.create({name: "Szczaw", product_category_id: 1})
Product.create({name: "Szczypiorek", product_category_id: 1})
Product.create({name: "Szparag", product_category_id: 1})
Product.create({name: "Szpinak", product_category_id: 1})
Product.create({name: "Ziemniak (kartofel, pyra)", product_category_id: 1})
Product.create({name: "Agrest", product_category_id: 2})
Product.create({name: "Ananas", product_category_id: 2})
Product.create({name: "Arbuz", product_category_id: 2})
Product.create({name: "Aronia", product_category_id: 2})
Product.create({name: "Awokado", product_category_id: 2})
Product.create({name: "Banan", product_category_id: 2})
Product.create({name: "Borówka", product_category_id: 2})
Product.create({name: "Brzoskwinia", product_category_id: 2})
Product.create({name: "Cytryna", product_category_id: 2})
Product.create({name: "Czarny bez", product_category_id: 2})
Product.create({name: "Czereśnia", product_category_id: 2})
Product.create({name: "Daktyl", product_category_id: 2})
Product.create({name: "Dereń", product_category_id: 2})
Product.create({name: "Dzika róża", product_category_id: 2})
Product.create({name: "Figa", product_category_id: 2})
Product.create({name: "Granat", product_category_id: 2})
Product.create({name: "Grejpfrut", product_category_id: 2})
Product.create({name: "Gruszka", product_category_id: 2})
Product.create({name: "Guawa", product_category_id: 2})
Product.create({name: "Jabłko", product_category_id: 2})
Product.create({name: "Jagoda", product_category_id: 2})
Product.create({name: "Jeżyna", product_category_id: 2})
Product.create({name: "Kaki", product_category_id: 2})
Product.create({name: "Kiwi", product_category_id: 2})
Product.create({name: "Kokos", product_category_id: 2})
Product.create({name: "Kumkwat", product_category_id: 2})
Product.create({name: "Liczi", product_category_id: 2})
Product.create({name: "Limonka", product_category_id: 2})
Product.create({name: "Malina", product_category_id: 2})
Product.create({name: "Mandarynka", product_category_id: 2})
Product.create({name: "Mango", product_category_id: 2})
Product.create({name: "Melon", product_category_id: 2})
Product.create({name: "Morela", product_category_id: 2})
Product.create({name: "Nektarynka", product_category_id: 2})
Product.create({name: "Opuncja", product_category_id: 2})
Product.create({name: "Orzech brazylijski", product_category_id: 2})
Product.create({name: "Orzech laskowy", product_category_id: 2})
Product.create({name: "Orzech piniowy", product_category_id: 2})
Product.create({name: "Orzech pistacjowy", product_category_id: 2})
Product.create({name: "Orzech włoski", product_category_id: 2})
Product.create({name: "Orzech ziemny", product_category_id: 2})
Product.create({name: "Papaja", product_category_id: 2})
Product.create({name: "Pigwa", product_category_id: 2})
Product.create({name: "Pomarańcza", product_category_id: 2})
Product.create({name: "Poziomka", product_category_id: 2})
Product.create({name: "Porzeczka", product_category_id: 2})
Product.create({name: "Renkloda", product_category_id: 2})
Product.create({name: "Rokitnik", product_category_id: 2})
Product.create({name: "Śliwka", product_category_id: 2})
Product.create({name: "Tarnina", product_category_id: 2})
Product.create({name: "Truskawka", product_category_id: 2})
Product.create({name: "Winogrono", product_category_id: 2})
Product.create({name: "Wiśnia", product_category_id: 2})
Product.create({name: "Żurawina", product_category_id: 2})
Product.create({name: "Środki do zmywarki", product_category_id: 3})
Product.create({name: "Detergenty do prania ", product_category_id: 3})
Product.create({name: "Środki do czyszczenia mebli ", product_category_id: 3})
Product.create({name: "Środki do czyszczenia toalet ", product_category_id: 3})
Product.create({name: "Płyny do mycia szyb", product_category_id: 3})
Product.create({name: "Środki do mycia naczyń ", product_category_id: 3})
Product.create({name: "Środki do czyszczenia podłóg ", product_category_id: 3})
Product.create({name: "Detergenty uniwersalne", product_category_id: 3})
Product.create({name: "mleko", product_category_id: 4})
Product.create({name: "jogurt", product_category_id: 4})
Product.create({name: "ser", product_category_id: 4})
Product.create({name: "maślanka", product_category_id: 4})
Product.create({name: "śmietana", product_category_id: 4})
Product.create({name: "kefir", product_category_id: 4})
Product.create({name: "masło", product_category_id: 4})
Product.create({name: "jajka", product_category_id: 4})
Product.create({name: "ryba mrożona", product_category_id: 5})
Product.create({name: "paluszki rybne", product_category_id: 5})
Product.create({name: "lody mrożone", product_category_id: 5})
Product.create({name: "pizza mrożona", product_category_id: 5})
Product.create({name: "pierogi mrożone", product_category_id: 5})
Product.create({name: "warzywa mrożone", product_category_id: 5})
Product.create({name: "frytki mrożone", product_category_id: 5})
Product.create({name: "szpinak mrożony", product_category_id: 5})
Product.create({name: "lasagne mrożona", product_category_id: 5})